---
apiVersion: v1
kind: Namespace
metadata:
  name: wordpress
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: password-generator
  namespace: wordpress
spec:
  length: 24
  symbolCharacters: "-_="
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mariadb
  namespace: wordpress
spec:
  refreshPolicy: CreatedOnce
  target:
    name: mariadb
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: password-generator
      rewrite:
        - transform:
            template: 'mariadb-root-{{ .value }}'
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: password-generator
      rewrite:
        - transform:
            template: 'mariadb-replication-{{ .value }}'
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: password-generator
      rewrite:
        - transform:
            template: 'mariadb-{{ .value }}'
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wordpress
  namespace: wordpress
spec:
  refreshPolicy: CreatedOnce
  target:
    name: wordpress
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: password-generator
      rewrite:
        - transform:
            template: 'wordpress-{{ .value }}'
