apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background
spec:
  project: default
  source:
    chart: wordpress
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 24.2.6
    helm:
      valuesObject:
        global:
          security:
            allowInsecureImages: true
        image:
          repository: bitnamilegacy/wordpress
          tag: 6.8.2-debian-12-r1
        wordpressPlugins: ~
        allowEmptyPassword: false
        allowOverrideNone: true
        wordpressScheme: https
        existingSecret: wordpress
        service:
          type: ClusterIP
        ingress:
          enabled: false
        persistence:
          enabled: true
          size: "2Gi"
          accessModes:
            - ReadWriteOnce
        volumePermissions:
          enabled: false
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "2000m"
            memory: "2Gi"
        mariadb:
          enabled: false
        externalDatabase:
          host: mariadb
          user: wordpress
          database: wordpress
          existingSecret: mariadb
        extraDeploy:
          - apiVersion: gateway.networking.k8s.io/v1
            kind: HTTPRoute
            metadata:
              name: wordpress-http
            spec:
              parentRefs:
                - name: default
                  namespace: traefik-system
                  sectionName: http
              hostnames:
                - wordpress.example.com
              rules:
                - filters:
                    - type: RequestRedirect
                      requestRedirect:
                        scheme: https
          - apiVersion: gateway.networking.k8s.io/v1
            kind: HTTPRoute
            metadata:
              name: wordpress-https
            spec:
              parentRefs:
                - name: default
                  namespace: traefik-system
                  sectionName: https
              hostnames:
                - wordpress.example.com
              rules:
                - matches:
                    - path:
                        type: PathPrefix
                        value: /
                  backendRefs:
                    - name: wordpress
                      port: 80
  destination:
    server: https://kubernetes.default.svc
    namespace: wordpress

  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
